const earningsData = {
  "programs": [
    {
      "cip": "050201",
      "label": "African American and African Diaspora Studies (BA)",
      "source": "African-American/Black Studies",
      "note": "",
      "graduates": null,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "050207",
      "label": "Women's, Gender, and Sexuality Studies (BA)",
      "source": "Women's Studies",
      "note": "",
      "graduates": null,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "090101",
      "label": "Communication Studies (BA)",
      "source": "Speech Communication & Rhetoric",
      "note": "",
      "graduates": 98,
      "employed": 72,
      "q1": 28174,
      "median": 40448,
      "q3": 56873
    },
    {
      "cip": "090102",
      "label": "Media Studies (BA)",
      "source": "Mass Communication/Media Studies",
      "note": "",
      "graduates": 80,
      "employed": 57,
      "q1": 24429,
      "median": 35467,
      "q3": 47650
    },
    {
      "cip": "110701",
      "label": "Computer Science (BS)",
      "source": "Computer Science",
      "note": "",
      "graduates": 56,
      "employed": 44,
      "q1": 47931,
      "median": 77961,
      "q3": 99958
    },
    {
      "cip": "110901",
      "label": "Information Systems and Supply Chain Management (BS)",
      "source": "Computer Systems Networking & Telecommunications",
      "note": "",
      "graduates": 102,
      "employed": 80,
      "q1": 41990,
      "median": 62029,
      "q3": 83991
    },
    {
      "cip": "131001",
      "label": "Special Education: General Curriculum (BS)",
      "source": "Special Education and Teaching, General",
      "note": "",
      "graduates": 25,
      "employed": 19,
      "q1": 46666,
      "median": 49429,
      "q3": 51530
    },
    {
      "cip": "131003",
      "label": "Professions in Deafness (B.S.)",
      "source": "Education/Teaching Of Individuals With Hearing Impairments Including Deafness",
      "note": "Historical degree name; now Interpreting, Deaf Education, and Advocacy Services.",
      "graduates": 19,
      "employed": 15,
      "q1": 32456,
      "median": 43081,
      "q3": 47671
    },
    {
      "cip": "131202",
      "label": "Elementary Education (K-6) (BS)",
      "source": "Elementary Education & Teaching",
      "note": "",
      "graduates": 48,
      "employed": 39,
      "q1": 44023,
      "median": 49465,
      "q3": 55251
    },
    {
      "cip": "131203",
      "label": "Middle Grades Education (BS)",
      "source": "Junior High/Intermediate/Middle School Education & Teaching",
      "note": "",
      "graduates": 11,
      "employed": 7,
      "q1": 44784,
      "median": 48831,
      "q3": 51754
    },
    {
      "cip": "131210",
      "label": "Early Childhood Development & Education (BS)",
      "source": "Early Childhood Education & Teaching",
      "note": "",
      "graduates": null,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "131302",
      "label": "Art Education (K-12) (BFA)",
      "source": "Art Teacher Education",
      "note": "",
      "graduates": null,
      "employed": null,
      "q1": 45484,
      "median": 46980,
      "q3": 49990
    },
    {
      "cip": "131305",
      "label": "English, Secondary Education (BA)",
      "source": "English/Language Arts Teacher Education",
      "note": "",
      "graduates": 7,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "131312",
      "label": "Music Education (BM)",
      "source": "Music Teacher Education",
      "note": "",
      "graduates": 20,
      "employed": 15,
      "q1": 48233,
      "median": 49843,
      "q3": 54844
    },
    {
      "cip": "131314",
      "label": "Physical Education, Teacher Education (B.S.)",
      "source": "Physical Education Teaching & Coaching",
      "note": "Historical degree name.",
      "graduates": null,
      "employed": null,
      "q1": 50439,
      "median": 53477,
      "q3": 54523
    },
    {
      "cip": "131317",
      "label": "Secondary education: Geography / Political Science / Psychology / Sociology (B.A.)",
      "source": "Social Science Teacher Education",
      "note": "Multiple historical degrees share this code.",
      "graduates": null,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "131318",
      "label": "History, Secondary Education (BA)",
      "source": "Social Studies Teacher Education",
      "note": "",
      "graduates": 7,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "160101",
      "label": "Languages, Literatures, and Cultures (B.A.)",
      "source": "Foreign Languages & Literatures, General",
      "note": "Historical degree name.",
      "graduates": 11,
      "employed": null,
      "q1": 12782,
      "median": 22959,
      "q3": 44697
    },
    {
      "cip": "160901",
      "label": "French — degree match unverified",
      "source": "French Language & Literature",
      "note": "Source program label retained; exact degree mapping is unverified.",
      "graduates": null,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "160905",
      "label": "Spanish (BA)",
      "source": "Spanish Language & Literature",
      "note": "",
      "graduates": 27,
      "employed": 21,
      "q1": 25244,
      "median": 45648,
      "q3": 61330
    },
    {
      "cip": "161200",
      "label": "Classical Studies (B.A.)",
      "source": "Classics & Classical Languages, Literatures & Linguistics, General",
      "note": "Historical degree name.",
      "graduates": 8,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "190701",
      "label": "Human Development and Family Studies (BS)",
      "source": "Human Development & Family Studies, General",
      "note": "",
      "graduates": null,
      "employed": 119,
      "q1": 31503,
      "median": 43665,
      "q3": 51984
    },
    {
      "cip": "190901",
      "label": "Consumer, Apparel, and Retail Studies (BS)",
      "source": "Apparel & Textiles, General",
      "note": "",
      "graduates": null,
      "employed": 42,
      "q1": 26256,
      "median": 45530,
      "q3": 58002
    },
    {
      "cip": "230101",
      "label": "English (BA)",
      "source": "English Language & Literature, General",
      "note": "",
      "graduates": 59,
      "employed": 40,
      "q1": 12374,
      "median": 39130,
      "q3": 51463
    },
    {
      "cip": "240101",
      "label": "Special Programs in Liberal Studies (B.A. / B.S.)",
      "source": "Liberal Arts & Sciences/Liberal Studies",
      "note": "Historical degrees; current successor is Liberal and Interdisciplinary Studies.",
      "graduates": 128,
      "employed": 91,
      "q1": 21370,
      "median": 43045,
      "q3": 58592
    },
    {
      "cip": "260101",
      "label": "Biology (BA) / Biology (BS)",
      "source": "Biology/Biological Sciences, General",
      "note": "",
      "graduates": 159,
      "employed": 110,
      "q1": 21975,
      "median": 41548,
      "q3": 57001
    },
    {
      "cip": "260202",
      "label": "Biochemistry (BS)",
      "source": "Biochemistry",
      "note": "",
      "graduates": 22,
      "employed": 12,
      "q1": 9546,
      "median": 29720,
      "q3": 40822
    },
    {
      "cip": "270101",
      "label": "Mathematics (BA) / Mathematics (BS)",
      "source": "Mathematics, General",
      "note": "",
      "graduates": 17,
      "employed": 9,
      "q1": 20963,
      "median": 36122,
      "q3": 51805
    },
    {
      "cip": "300501",
      "label": "Peace and Conflict Studies (BA)",
      "source": "Peace Studies & Conflict Resolution",
      "note": "",
      "graduates": null,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "301901",
      "label": "Nutrition (BS)",
      "source": "Nutrition Sciences",
      "note": "",
      "graduates": 47,
      "employed": 33,
      "q1": 36875,
      "median": 45535,
      "q3": 57665
    },
    {
      "cip": "309999",
      "label": "Interdisciplinary studies — degree match unverified",
      "source": "Multi-/Interdisciplinary Studies, Other",
      "note": "Source program label retained; exact degree mapping is unverified.",
      "graduates": null,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "310101",
      "label": "Recreation and Parks Management (B.S.)",
      "source": "Parks, Recreation & Leisure Studies",
      "note": "Historical name; now Sport Management and Recreational Therapy.",
      "graduates": 92,
      "employed": 68,
      "q1": 22331,
      "median": 40217,
      "q3": 48050
    },
    {
      "cip": "310505",
      "label": "Kinesiology (B.S.)",
      "source": "Exercise Science and Kinesiology",
      "note": "Historical reporting code.",
      "graduates": 155,
      "employed": 112,
      "q1": 25154,
      "median": 40230,
      "q3": 58858
    },
    {
      "cip": "380101",
      "label": "Philosophy (BA)",
      "source": "Philosophy",
      "note": "",
      "graduates": 15,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "380201",
      "label": "Religious Studies (B.A.)",
      "source": "Religion/Religious Studies",
      "note": "Historical degree name.",
      "graduates": 6,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "400501",
      "label": "Chemistry (BA) / Chemistry (BS)",
      "source": "Chemistry, General",
      "note": "",
      "graduates": null,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "400801",
      "label": "Physics (B.A. / B.S.)",
      "source": "Physics, General",
      "note": "Historical degree names.",
      "graduates": null,
      "employed": null,
      "q1": null,
      "median": null,
      "q3": null
    },
    {
      "cip": "420101",
      "label": "Psychology (BA) / Psychology (BS)",
      "source": "Psychology, General",
      "note": "",
      "graduates": 184,
      "employed": 133,
      "q1": 24995,
      "median": 37089,
      "q3": 49577
    },
    {
      "cip": "440701",
      "label": "Social Work (BSW)",
      "source": "Social Work",
      "note": "",
      "graduates": 90,
      "employed": 76,
      "q1": 37820,
      "median": 44091,
      "q3": 51919
    },
    {
      "cip": "450201",
      "label": "Anthropology (B.A.)",
      "source": "Anthropology, General",
      "note": "Former major, discontinued in 2024–25.",
      "graduates": 27,
      "employed": 18,
      "q1": 30037,
      "median": 39597,
      "q3": 49047
    },
    {
      "cip": "450601",
      "label": "Economics (BA)",
      "source": "Economics, General",
      "note": "",
      "graduates": 16,
      "employed": 8,
      "q1": 19458,
      "median": 60366,
      "q3": 84748
    },
    {
      "cip": "450701",
      "label": "Geography (B.A.)",
      "source": "Geography",
      "note": "Historical B.A. cohort; the B.S. began later.",
      "graduates": 17,
      "employed": 12,
      "q1": 17154,
      "median": 35151,
      "q3": 46395
    },
    {
      "cip": "451001",
      "label": "Political Science (BA)",
      "source": "Political Science & Government, General",
      "note": "",
      "graduates": 59,
      "employed": 39,
      "q1": 31073,
      "median": 43851,
      "q3": 51886
    },
    {
      "cip": "451101",
      "label": "Sociology (BA)",
      "source": "Sociology, General",
      "note": "",
      "graduates": 124,
      "employed": 90,
      "q1": 23743,
      "median": 38444,
      "q3": 47917
    },
    {
      "cip": "500301",
      "label": "Dance Studies (B.A.) / Dance (B.F.A.)",
      "source": "Dance, General",
      "note": "Both degrees share this reporting code.",
      "graduates": 23,
      "employed": 10,
      "q1": 39505,
      "median": 44207,
      "q3": 49246
    },
    {
      "cip": "500408",
      "label": "Interior Architecture (B.F.A.)",
      "source": "Interior Design",
      "note": "Historical name; now Interior Architecture and Design.",
      "graduates": 33,
      "employed": 19,
      "q1": 38323,
      "median": 55921,
      "q3": 64041
    },
    {
      "cip": "500501",
      "label": "Drama (BA) / Drama (BFA)",
      "source": "Drama & Dramatics/Theatre Arts, General",
      "note": "",
      "graduates": 58,
      "employed": 30,
      "q1": 13079,
      "median": 28379,
      "q3": 46846
    },
    {
      "cip": "500701",
      "label": "Art (BA)",
      "source": "Art/Art Studies, General",
      "note": "",
      "graduates": 16,
      "employed": 8,
      "q1": 17888,
      "median": 23870,
      "q3": 42437
    },
    {
      "cip": "500702",
      "label": "Studio Art (BFA)",
      "source": "Fine/Studio Arts, General",
      "note": "",
      "graduates": 65,
      "employed": 47,
      "q1": 15233,
      "median": 35618,
      "q3": 43378
    },
    {
      "cip": "500901",
      "label": "Music (BA)",
      "source": "Music, General",
      "note": "",
      "graduates": null,
      "employed": 9,
      "q1": 33466,
      "median": 35946,
      "q3": 39593
    },
    {
      "cip": "500903",
      "label": "Performance (B.M.)",
      "source": "Music Performance, General",
      "note": "Historical degree name.",
      "graduates": 25,
      "employed": 11,
      "q1": 28638,
      "median": 35254,
      "q3": 38004
    },
    {
      "cip": "501002",
      "label": "Arts Administration (BA)",
      "source": "Fine & Studio Arts Management",
      "note": "",
      "graduates": null,
      "employed": 11,
      "q1": 8628,
      "median": 35254,
      "q3": 46435
    },
    {
      "cip": "510204",
      "label": "Speech Pathology and Audiology (BS)",
      "source": "Audiology/Audiologist & Speech-Language Pathology/Pathologist",
      "note": "",
      "graduates": 44,
      "employed": 30,
      "q1": 28983,
      "median": 43751,
      "q3": 59739
    },
    {
      "cip": "512207",
      "label": "Public Health Education (B.S.)",
      "source": "Public Health Education & Promotion",
      "note": "",
      "graduates": 51,
      "employed": 41,
      "q1": 40381,
      "median": 50843,
      "q3": 65284
    },
    {
      "cip": "513801",
      "label": "Nursing (BSN)",
      "source": "Registered Nursing/Registered Nurse",
      "note": "",
      "graduates": 231,
      "employed": 197,
      "q1": 55903,
      "median": 70540,
      "q3": 92193
    },
    {
      "cip": "520201",
      "label": "Business Administration (B.S.) / Marketing (B.S.)",
      "source": "Business Administration & Management, General",
      "note": "Both degrees used this code in the historical inventory; earnings cannot be separated.",
      "graduates": 393,
      "employed": 307,
      "q1": 38794,
      "median": 52466,
      "q3": 70427
    },
    {
      "cip": "520301",
      "label": "Accounting (BS)",
      "source": "Accounting",
      "note": "",
      "graduates": 54,
      "employed": 41,
      "q1": 39283,
      "median": 52698,
      "q3": 65935
    },
    {
      "cip": "520601",
      "label": "Economics (BS)",
      "source": "Business/Managerial Economics",
      "note": "",
      "graduates": null,
      "employed": 17,
      "q1": 42226,
      "median": 53247,
      "q3": 64182
    },
    {
      "cip": "520701",
      "label": "Entrepreneurship (BS)",
      "source": "Entrepreneurship/Entrepreneurial Studies",
      "note": "",
      "graduates": null,
      "employed": null,
      "q1": 16285,
      "median": 45088,
      "q3": 47157
    },
    {
      "cip": "520801",
      "label": "Finance (BS)",
      "source": "Finance, General",
      "note": "",
      "graduates": 69,
      "employed": 54,
      "q1": 44849,
      "median": 59913,
      "q3": 74500
    },
    {
      "cip": "520901",
      "label": "Sustainable Tourism and Hospitality (B.A.) / Hospitality and Tourism Management (B.S.)",
      "source": "Hospitality Administration/Management, General",
      "note": "Historical reporting group; degrees cannot be separated.",
      "graduates": 20,
      "employed": null,
      "q1": 36971,
      "median": 41733,
      "q3": 48616
    },
    {
      "cip": "521101",
      "label": "International Business Studies (BS)",
      "source": "International Business/Trade/Commerce",
      "note": "",
      "graduates": 36,
      "employed": 25,
      "q1": 40390,
      "median": 49477,
      "q3": 60170
    },
    {
      "cip": "540101",
      "label": "History (BA)",
      "source": "History, General",
      "note": "",
      "graduates": 35,
      "employed": 27,
      "q1": 20228,
      "median": 33960,
      "q3": 38147
    }
  ],
  "references": [
    {
      "kind": "reference",
      "cip": "hs-nc",
      "label": "High school graduates — North Carolina",
      "shortLabel": "NC HS",
      "q1": 20390,
      "median": 33240,
      "q3": 47713,
      "sampleCount": 7834,
      "populationEstimate": 221507,
      "dollarsYear": 2023,
      "period": "2019–2023"
    },
    {
      "kind": "reference",
      "cip": "hs-us",
      "label": "High school graduates — U.S.",
      "shortLabel": "U.S. HS",
      "q1": 22791,
      "median": 35614,
      "q3": 50976,
      "sampleCount": 287579,
      "populationEstimate": 7626652,
      "dollarsYear": 2023,
      "period": "2019–2023"
    }
  ]
};
